//
// Created by Utilisateur on 2026-04-24.
//

#ifndef PROJET_HOCKEY_SIMULATOR_PERSONNE_H
#define PROJET_HOCKEY_SIMULATOR_PERSONNE_H


class Personne {
};


#endif //PROJET_HOCKEY_SIMULATOR_PERSONNE_H